# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

split_node <- function(X, Y, m_feature, Index, i, Model, min_leaf, Inv_Cov_Y, Command) {
    .Call('MultivariateRandomForest_split_node', PACKAGE = 'MultivariateRandomForest', X, Y, m_feature, Index, i, Model, min_leaf, Inv_Cov_Y, Command)
}

splitt <- function(X, Y, m_feature, Index, Inv_Cov_Y, Command, ff) {
    .Call('MultivariateRandomForest_splitt', PACKAGE = 'MultivariateRandomForest', X, Y, m_feature, Index, Inv_Cov_Y, Command, ff)
}

Node_cost <- function(y, Inv_Cov_Y, Command) {
    .Call('MultivariateRandomForest_Node_cost', PACKAGE = 'MultivariateRandomForest', y, Inv_Cov_Y, Command)
}

predicting <- function(Single_Model, i, xt, Variable_number) {
    .Call('MultivariateRandomForest_predicting', PACKAGE = 'MultivariateRandomForest', Single_Model, i, xt, Variable_number)
}

